import { ObjectValues } from "../../types";

export const STORE_CONFIG_STEPS = {
  OWNER: "OWNER",
  FLEXIBILITY: "FLEXIBILITY",
  SCHEDULE_TYPE: "SCHEDULE_TYPE",
  SIMULTANEOUS: "SIMULTANEOUS",
  UNIQUENESS: "UNIQUENESS",
  SPECIFIC_RESERVATION: "SPECIFIC_RESERVATION",
  PERIODICITY: "PERIODICITY",
  CUSTOM_ATTRIBUTES_SPEC: "CUSTOM_ATTRIBUTES_SPEC",
  MAIN_PAGE: "MAIN_PAGE",
  DETAILS_PAGE: "DETAILS_PAGE",
  PRINT_STORE_CONFIG: "PRINT_STORE_CONFIG",
} as const;

export type StoreConfigStep = ObjectValues<typeof STORE_CONFIG_STEPS>;
