import { ObjectValues } from "../../../types";

export const STORE_CONFIG_STEPS = {
  GENERAL_STORE_INFO: "GENERAL_STORE_INFO",
  FLEXIBILITY: "FLEXIBILITY",
  GRANULARITY: "GRANULARITY",
  ALLOW_OVER_NIGHT: "ALLOW_OVER_NIGHT",
  SIMULTANEOUS: "SIMULTANEOUS",
  UNIQUENESS: "UNIQUENESS",
  SPECIFIC_RESERVATION: "SPECIFIC_RESERVATION",
  PERIODICITY: "PERIODICITY",
  CUSTOM_ATTRIBUTES_SPEC: "CUSTOM_ATTRIBUTES_SPEC",
  MAIN_PAGE: "MAIN_PAGE",
  DETAILS_PAGE: "DETAILS_PAGE",
  AUTH_CONFIG: "AUTH_CONFIG",
  SUMMARY: "SUMMARY",
} as const;

export type StoreConfigStep = ObjectValues<typeof STORE_CONFIG_STEPS>;
