version: "3.8"
services:
  front:
    build: .
    container_name: zpi-front
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
  keycloak:
    image: johnbg71/configured_keycloak:version1
    container_name: zpi-keycloak
    ports:
      - "4000:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin